"""Update task model with status and timestamps

Revision ID: 041859266aaf
Revises: 1b38652e1a23
Create Date: 2025-07-25 19:18:08.078692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '041859266aaf'
down_revision: Union[str, Sequence[str], None] = '1b38652e1a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('project', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('tasks_column_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'column_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('column_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('tasks_column_id_fkey'), 'tasks', 'columns', ['column_id'], ['id'])
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    op.drop_column('tasks', 'project')
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###
